# Generated by Django 4.2.18 on 2025-01-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
