# Generated by Django 4.2.18 on 2025-01-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
