# Generated by Django 4.2.18 on 2025-01-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='doctor@doctor.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
