# Generated by Django 4.2.18 on 2025-01-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='insight',
            field=models.TextField(blank=True, default='Monitor your key health metrics'),
        ),
    ]
